apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
  namespace: sonarqube
  labels:
    app: postgresql
    component: database
type: Opaque
data:
  # Password: sonarqube123 (base64 encoded)
  # To generate: echo -n 'sonarqube123' | base64
  postgres-password: c29uYXJxdWJlMTIz